// Code generated by securitygen; DO NOT EDIT.

package security

import (
	context "context"
	sha256 "crypto/sha256"
	subtle "crypto/subtle"
	errors "errors"
	fmt "fmt"
	api "ogen-sec/internal/ogen/api"
	slices "slices"
	time "time"
)

// APIKeyStore finds credentials within a scheme's namespace using a SHA-256 digest.
// scheme is the Go credential type name, for example ApiKeyHeaderA3nKs.
// Implementations must return ErrInvalidAPIKey for an unknown key and must be
// safe for concurrent use. The raw key is never passed to the store.
type APIKeyStore interface {
	LookupAPIKey(ctx context.Context, scheme string, hash [sha256.Size]byte) (APIKeyRecord, error)
}

// APIKeyRecord describes a randomly generated, high-entropy API key.
// Hash is SHA-256 of the original key. A zero ExpiresAt means no expiration.
type APIKeyRecord struct {
	Hash      [sha256.Size]byte
	Subject   string
	Roles     []string
	ExpiresAt time.Time
	Revoked   bool
}

var (
	ErrInvalidAPIKey            = errors.New("invalid API key")
	ErrAPIKeyForbidden          = errors.New("insufficient API key roles")
	ErrAPIKeyStoreNotConfigured = errors.New("API key store is not configured")
)

// APIKeyIdentity contains verified identity information, without credentials.
type APIKeyIdentity struct {
	Subject string
	Roles   []string
}

type apiKeyContextKey struct{ scheme string }

// APIKeyIdentityFromContext returns the identity authenticated for a scheme.
// Identities for other schemes are preserved when several API keys are required.
func APIKeyIdentityFromContext(ctx context.Context, scheme string) (APIKeyIdentity, bool) {
	identity, ok := ctx.Value(apiKeyContextKey{scheme: scheme}).(APIKeyIdentity)
	identity.Roles = slices.Clone(identity.Roles)
	return identity, ok
}

func (s *passthroughSecurityHandler) authorizeAPIKey(ctx context.Context, scheme, key string, requiredRoles []string) (context.Context, error) {
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if key == "" {
		return ctx, ErrInvalidAPIKey
	}
	if s.apiKeys == nil {
		return ctx, ErrAPIKeyStoreNotConfigured
	}
	hash := sha256.Sum256([]byte(key))
	record, err := s.apiKeys.LookupAPIKey(ctx, scheme, hash)
	if err != nil {
		return ctx, fmt.Errorf("lookup API key: %w", err)
	}
	if subtle.ConstantTimeCompare(hash[:], record.Hash[:]) != 1 || record.Revoked {
		return ctx, ErrInvalidAPIKey
	}
	if !record.ExpiresAt.IsZero() && !time.Now().Before(record.ExpiresAt) {
		return ctx, ErrInvalidAPIKey
	}
	for _, role := range requiredRoles {
		if !slices.Contains(record.Roles, role) {
			return ctx, ErrAPIKeyForbidden
		}
	}
	identity := APIKeyIdentity{Subject: record.Subject, Roles: slices.Clone(record.Roles)}
	return context.WithValue(ctx, apiKeyContextKey{scheme: scheme}, identity), nil
}

// BasicAuthStore finds a user within a scheme's namespace by username.
// scheme is the Go credential type name. Implementations must return
// ErrInvalidBasicAuth for an unknown user and be safe for concurrent use.
// Plaintext passwords are never passed to the store.
type BasicAuthStore interface {
	LookupBasicAuth(ctx context.Context, scheme, username string) (BasicAuthRecord, error)
}

// BasicAuthRecord describes a user and their encoded password hash.
// PasswordHash includes the algorithm, salt and cost parameters required by
// PasswordVerifier. A zero ExpiresAt means no expiration.
type BasicAuthRecord struct {
	PasswordHash string
	Subject      string
	Roles        []string
	Disabled     bool
	ExpiresAt    time.Time
}

// PasswordVerifier verifies an encoded password hash, for example Argon2id or bcrypt.
// Return (false, nil) for a mismatch, and an error for verification failures.
// For an empty passwordHash, perform a dummy verification with the same cost
// as a normal password check, then return (false, nil). This is used for unknown
// users. Implementations must be safe for concurrent use and never log passwords.
type PasswordVerifier interface {
	VerifyPassword(ctx context.Context, passwordHash, password string) (bool, error)
}

var (
	ErrInvalidBasicAuth              = errors.New("invalid basic auth credentials")
	ErrBasicAuthForbidden            = errors.New("insufficient basic auth roles")
	ErrBasicAuthStoreNotConfigured   = errors.New("basic auth store is not configured")
	ErrPasswordVerifierNotConfigured = errors.New("password verifier is not configured")
)

// BasicAuthIdentity contains verified user information, without credentials.
type BasicAuthIdentity struct {
	Subject  string
	Username string
	Roles    []string
}

type basicAuthContextKey struct{ scheme string }

// BasicAuthIdentityFromContext returns the user authenticated for a scheme.
func BasicAuthIdentityFromContext(ctx context.Context, scheme string) (BasicAuthIdentity, bool) {
	identity, ok := ctx.Value(basicAuthContextKey{scheme: scheme}).(BasicAuthIdentity)
	identity.Roles = slices.Clone(identity.Roles)
	return identity, ok
}

func (s *passthroughSecurityHandler) authorizeBasicAuth(ctx context.Context, scheme, username, password string, requiredRoles []string) (context.Context, error) {
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if username == "" || password == "" {
		return ctx, ErrInvalidBasicAuth
	}
	if s.basicAuth == nil {
		return ctx, ErrBasicAuthStoreNotConfigured
	}
	if s.passwords == nil {
		return ctx, ErrPasswordVerifierNotConfigured
	}
	record, err := s.basicAuth.LookupBasicAuth(ctx, scheme, username)
	if err != nil {
		if !errors.Is(err, ErrInvalidBasicAuth) {
			return ctx, fmt.Errorf("lookup basic auth user: %w", err)
		}
		// Discard any record returned with an unknown-user error. The empty hash
		// requests a dummy password check and cannot authorize the request.
		record = BasicAuthRecord{}
	}
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	valid, err := s.passwords.VerifyPassword(ctx, record.PasswordHash, password)
	if err != nil {
		return ctx, fmt.Errorf("verify basic auth password: %w", err)
	}
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if !valid || record.PasswordHash == "" || record.Disabled {
		return ctx, ErrInvalidBasicAuth
	}
	if !record.ExpiresAt.IsZero() && !time.Now().Before(record.ExpiresAt) {
		return ctx, ErrInvalidBasicAuth
	}
	for _, role := range requiredRoles {
		if !slices.Contains(record.Roles, role) {
			return ctx, ErrBasicAuthForbidden
		}
	}
	identity := BasicAuthIdentity{Subject: record.Subject, Username: username, Roles: slices.Clone(record.Roles)}
	return context.WithValue(ctx, basicAuthContextKey{scheme: scheme}, identity), nil
}

// passthroughSecurityHandler implements api.SecurityHandler. Unsupported schemes remain stubs.
type passthroughSecurityHandler struct {
	apiKeys   APIKeyStore
	basicAuth BasicAuthStore
	passwords PasswordVerifier
}

// NewPassthroughSecurityHandler creates a security handler. Nil dependencies reject requests for their schemes.
func NewPassthroughSecurityHandler(apiKeys APIKeyStore, basicAuth BasicAuthStore, passwords PasswordVerifier) *passthroughSecurityHandler {
	return &passthroughSecurityHandler{apiKeys: apiKeys, basicAuth: basicAuth, passwords: passwords}
}

var _ api.SecurityHandler = (*passthroughSecurityHandler)(nil)

// HandleApiKeyCookieM2xJf implements api.SecurityHandler.
func (s *passthroughSecurityHandler) HandleApiKeyCookieM2xJf(ctx context.Context, _ api.OperationName, credentials api.ApiKeyCookieM2xJf) (context.Context, error) {
	return s.authorizeAPIKey(ctx, "ApiKeyCookieM2xJf", credentials.APIKey, credentials.Roles)
}

// HandleApiKeyHeaderA3nKs implements api.SecurityHandler.
func (s *passthroughSecurityHandler) HandleApiKeyHeaderA3nKs(ctx context.Context, _ api.OperationName, credentials api.ApiKeyHeaderA3nKs) (context.Context, error) {
	return s.authorizeAPIKey(ctx, "ApiKeyHeaderA3nKs", credentials.APIKey, credentials.Roles)
}

// HandleApiKeyQueryC8rVw implements api.SecurityHandler.
func (s *passthroughSecurityHandler) HandleApiKeyQueryC8rVw(ctx context.Context, _ api.OperationName, credentials api.ApiKeyQueryC8rVw) (context.Context, error) {
	return s.authorizeAPIKey(ctx, "ApiKeyQueryC8rVw", credentials.APIKey, credentials.Roles)
}

// HandleBasicAuthF5wJz implements api.SecurityHandler.
func (s *passthroughSecurityHandler) HandleBasicAuthF5wJz(ctx context.Context, _ api.OperationName, credentials api.BasicAuthF5wJz) (context.Context, error) {
	return s.authorizeBasicAuth(ctx, "BasicAuthF5wJz", credentials.Username, credentials.Password, credentials.Roles)
}

// HandleBearerAuthV6qPt implements api.SecurityHandler.
func (*passthroughSecurityHandler) HandleBearerAuthV6qPt(ctx context.Context, operationName api.OperationName, t api.BearerAuthV6qPt) (context.Context, error) {
	panic("HandleBearerAuthV6qPt: not implemented")
}

// HandleOAuth2N4kXb implements api.SecurityHandler.
func (*passthroughSecurityHandler) HandleOAuth2N4kXb(ctx context.Context, operationName api.OperationName, t api.OAuth2N4kXb) (context.Context, error) {
	panic("HandleOAuth2N4kXb: not implemented")
}

// HandleReferencedBearerAuthZ8yHd implements api.SecurityHandler.
func (*passthroughSecurityHandler) HandleReferencedBearerAuthZ8yHd(ctx context.Context, operationName api.OperationName, t api.ReferencedBearerAuthZ8yHd) (context.Context, error) {
	panic("HandleReferencedBearerAuthZ8yHd: not implemented")
}
