// Code generated by securitygen; DO NOT EDIT.

package security

import (
	context "context"
	sha256 "crypto/sha256"
	subtle "crypto/subtle"
	errors "errors"
	api "example.test/generated/api"
	fmt "fmt"
	slices "slices"
	time "time"
)

// APIKeyStore finds credentials within a scheme's namespace using a SHA-256 digest.
// scheme is the Go credential type name, for example ApiKeyHeaderA3nKs.
// Implementations must return ErrInvalidAPIKey for an unknown key and must be
// safe for concurrent use. The raw key is never passed to the store.
type APIKeyStore interface {
	LookupAPIKey(ctx context.Context, scheme string, hash [sha256.Size]byte) (APIKeyRecord, error)
}

// APIKeyRecord describes a randomly generated, high-entropy API key.
// Hash is SHA-256 of the original key. A zero ExpiresAt means no expiration.
type APIKeyRecord struct {
	Hash      [sha256.Size]byte
	Subject   string
	Roles     []string
	ExpiresAt time.Time
	Revoked   bool
}

var (
	ErrInvalidAPIKey            = errors.New("invalid API key")
	ErrAPIKeyForbidden          = errors.New("insufficient API key roles")
	ErrAPIKeyStoreNotConfigured = errors.New("API key store is not configured")
)

// APIKeyIdentity contains verified identity information, without credentials.
type APIKeyIdentity struct {
	Subject string
	Roles   []string
}

type apiKeyContextKey struct{ scheme string }

// APIKeyIdentityFromContext returns the identity authenticated for a scheme.
// Identities for other schemes are preserved when several API keys are required.
func APIKeyIdentityFromContext(ctx context.Context, scheme string) (APIKeyIdentity, bool) {
	identity, ok := ctx.Value(apiKeyContextKey{scheme: scheme}).(APIKeyIdentity)
	identity.Roles = slices.Clone(identity.Roles)
	return identity, ok
}

func (s *handler) authorizeAPIKey(ctx context.Context, scheme, key string, requiredRoles []string) (context.Context, error) {
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if key == "" {
		return ctx, ErrInvalidAPIKey
	}
	if s.apiKeys == nil {
		return ctx, ErrAPIKeyStoreNotConfigured
	}
	hash := sha256.Sum256([]byte(key))
	record, err := s.apiKeys.LookupAPIKey(ctx, scheme, hash)
	if err != nil {
		return ctx, fmt.Errorf("lookup API key: %w", err)
	}
	if subtle.ConstantTimeCompare(hash[:], record.Hash[:]) != 1 || record.Revoked {
		return ctx, ErrInvalidAPIKey
	}
	if !record.ExpiresAt.IsZero() && !time.Now().Before(record.ExpiresAt) {
		return ctx, ErrInvalidAPIKey
	}
	for _, role := range requiredRoles {
		if !slices.Contains(record.Roles, role) {
			return ctx, ErrAPIKeyForbidden
		}
	}
	identity := APIKeyIdentity{Subject: record.Subject, Roles: slices.Clone(record.Roles)}
	return context.WithValue(ctx, apiKeyContextKey{scheme: scheme}, identity), nil
}

// BasicAuthStore finds a user within a scheme's namespace by username.
// scheme is the Go credential type name. Implementations must return
// ErrInvalidBasicAuth for an unknown user and be safe for concurrent use.
// Plaintext passwords are never passed to the store.
type BasicAuthStore interface {
	LookupBasicAuth(ctx context.Context, scheme, username string) (BasicAuthRecord, error)
}

// BasicAuthRecord describes a user and their encoded password hash.
// PasswordHash includes the algorithm, salt and cost parameters required by
// PasswordVerifier. A zero ExpiresAt means no expiration.
type BasicAuthRecord struct {
	PasswordHash string
	Subject      string
	Roles        []string
	Disabled     bool
	ExpiresAt    time.Time
}

// PasswordVerifier verifies an encoded password hash, for example Argon2id or bcrypt.
// Return (false, nil) for a mismatch, and an error for verification failures.
// For an empty passwordHash, perform a dummy verification with the same cost
// as a normal password check, then return (false, nil). This is used for unknown
// users. Implementations must be safe for concurrent use and never log passwords.
type PasswordVerifier interface {
	VerifyPassword(ctx context.Context, passwordHash, password string) (bool, error)
}

var (
	ErrInvalidBasicAuth              = errors.New("invalid basic auth credentials")
	ErrBasicAuthForbidden            = errors.New("insufficient basic auth roles")
	ErrBasicAuthStoreNotConfigured   = errors.New("basic auth store is not configured")
	ErrPasswordVerifierNotConfigured = errors.New("password verifier is not configured")
)

// BasicAuthIdentity contains verified user information, without credentials.
type BasicAuthIdentity struct {
	Subject  string
	Username string
	Roles    []string
}

type basicAuthContextKey struct{ scheme string }

// BasicAuthIdentityFromContext returns the user authenticated for a scheme.
func BasicAuthIdentityFromContext(ctx context.Context, scheme string) (BasicAuthIdentity, bool) {
	identity, ok := ctx.Value(basicAuthContextKey{scheme: scheme}).(BasicAuthIdentity)
	identity.Roles = slices.Clone(identity.Roles)
	return identity, ok
}

func (s *handler) authorizeBasicAuth(ctx context.Context, scheme, username, password string, requiredRoles []string) (context.Context, error) {
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if username == "" || password == "" {
		return ctx, ErrInvalidBasicAuth
	}
	if s.basicAuth == nil {
		return ctx, ErrBasicAuthStoreNotConfigured
	}
	if s.passwords == nil {
		return ctx, ErrPasswordVerifierNotConfigured
	}
	record, err := s.basicAuth.LookupBasicAuth(ctx, scheme, username)
	if err != nil {
		if !errors.Is(err, ErrInvalidBasicAuth) {
			return ctx, fmt.Errorf("lookup basic auth user: %w", err)
		}
		// Discard any record returned with an unknown-user error. The empty hash
		// requests a dummy password check and cannot authorize the request.
		record = BasicAuthRecord{}
	}
	valid, err := s.passwords.VerifyPassword(ctx, record.PasswordHash, password)
	if err != nil {
		return ctx, fmt.Errorf("verify basic auth password: %w", err)
	}
	if !valid || record.PasswordHash == "" || record.Disabled {
		return ctx, ErrInvalidBasicAuth
	}
	if !record.ExpiresAt.IsZero() && !time.Now().Before(record.ExpiresAt) {
		return ctx, ErrInvalidBasicAuth
	}
	for _, role := range requiredRoles {
		if !slices.Contains(record.Roles, role) {
			return ctx, ErrBasicAuthForbidden
		}
	}
	identity := BasicAuthIdentity{Subject: record.Subject, Username: username, Roles: slices.Clone(record.Roles)}
	return context.WithValue(ctx, basicAuthContextKey{scheme: scheme}, identity), nil
}

// BearerTokenVerifier authenticates a token within a scheme's trust boundary.
// scheme is the Go credential type name, not the operation name. Return
// ErrInvalidBearerToken for invalid or unknown tokens, including inactive,
// revoked, expired or not-yet-valid tokens. Return only verified, trusted
// identity information.
// JWT implementations must verify signatures using allowed algorithms and
// trusted keys, and validate the expected issuer, audience and required claims.
// Opaque token implementations must use a trusted store or introspection service.
// Implementations must be safe for concurrent use, honor context cancellation,
// and never log raw tokens or include them in errors.
type BearerTokenVerifier interface {
	VerifyBearerToken(ctx context.Context, scheme, token string) (subject string, roles []string, err error)
}

var (
	ErrInvalidBearerToken               = errors.New("invalid bearer token")
	ErrBearerAuthForbidden              = errors.New("insufficient bearer auth roles")
	ErrBearerTokenVerifierNotConfigured = errors.New("bearer token verifier is not configured")
)

// BearerAuthIdentity contains verified identity information, without the token.
type BearerAuthIdentity struct {
	Subject string
	Roles   []string
}

type bearerAuthContextKey struct{ scheme string }

// BearerAuthIdentityFromContext returns the identity authenticated for a scheme.
func BearerAuthIdentityFromContext(ctx context.Context, scheme string) (BearerAuthIdentity, bool) {
	identity, ok := ctx.Value(bearerAuthContextKey{scheme: scheme}).(BearerAuthIdentity)
	identity.Roles = slices.Clone(identity.Roles)
	return identity, ok
}

func (s *handler) authorizeBearerAuth(ctx context.Context, scheme, token string, requiredRoles []string) (context.Context, error) {
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if token == "" {
		return ctx, ErrInvalidBearerToken
	}
	if s.bearerTokens == nil {
		return ctx, ErrBearerTokenVerifierNotConfigured
	}
	subject, roles, err := s.bearerTokens.VerifyBearerToken(ctx, scheme, token)
	if err != nil {
		return ctx, fmt.Errorf("verify bearer token: %w", err)
	}
	for _, role := range requiredRoles {
		if !slices.Contains(roles, role) {
			return ctx, ErrBearerAuthForbidden
		}
	}
	identity := BearerAuthIdentity{Subject: subject, Roles: slices.Clone(roles)}
	return context.WithValue(ctx, bearerAuthContextKey{scheme: scheme}, identity), nil
}

// OAuth2TokenVerifier authenticates an access token for this resource server.
// scheme is the Go credential type name, not the operation name. Return
// ErrInvalidOAuth2Token for invalid or unknown tokens. Return only verified
// identity information and granted scopes, with Active explicitly set to true.
// JWT implementations must verify signatures with trusted keys and allowed
// algorithms, and validate the expected issuer, audience and required claims.
// Opaque tokens require a trusted store or authenticated introspection service.
// Reject refresh tokens and ID tokens: only access tokens intended for this API
// are valid. Implementations must be safe for concurrent use, honor cancellation,
// and never log raw tokens or include them in errors.
type OAuth2TokenVerifier interface {
	VerifyOAuth2Token(ctx context.Context, scheme, token string) (OAuth2TokenRecord, error)
}

// OAuth2TokenRecord contains verified access token information, not the token.
// Active must be false for revoked/inactive tokens; the zero record rejects access.
// Scopes are actual granted permissions, not the operation's requirements.
// Zero NotBefore/ExpiresAt values mean no corresponding time restriction; the
// verifier must enforce any requirement for these claims before returning.
type OAuth2TokenRecord struct {
	Active    bool
	Subject   string
	ClientID  string
	Scopes    []string
	NotBefore time.Time
	ExpiresAt time.Time
}

var (
	ErrInvalidOAuth2Token               = errors.New("invalid OAuth2 access token")
	ErrOAuth2Forbidden                  = errors.New("insufficient OAuth2 scopes")
	ErrOAuth2TokenVerifierNotConfigured = errors.New("OAuth2 token verifier is not configured")
)

// OAuth2Identity contains verified identity information, without the access token.
// Subject may be empty for tokens identifying only a client via ClientID.
type OAuth2Identity struct {
	Subject  string
	ClientID string
	Scopes   []string
}

type oauth2ContextKey struct{ scheme string }

// OAuth2IdentityFromContext returns the identity authenticated for a scheme.
func OAuth2IdentityFromContext(ctx context.Context, scheme string) (OAuth2Identity, bool) {
	identity, ok := ctx.Value(oauth2ContextKey{scheme: scheme}).(OAuth2Identity)
	identity.Scopes = slices.Clone(identity.Scopes)
	return identity, ok
}

func (s *handler) authorizeOAuth2(ctx context.Context, scheme, token string, requiredScopes []string) (context.Context, error) {
	if err := ctx.Err(); err != nil {
		return ctx, err
	}
	if token == "" {
		return ctx, ErrInvalidOAuth2Token
	}
	if s.oauth2Tokens == nil {
		return ctx, ErrOAuth2TokenVerifierNotConfigured
	}
	record, err := s.oauth2Tokens.VerifyOAuth2Token(ctx, scheme, token)
	if err != nil {
		return ctx, fmt.Errorf("verify OAuth2 access token: %w", err)
	}
	if !record.Active {
		return ctx, ErrInvalidOAuth2Token
	}
	now := time.Now()
	if !record.NotBefore.IsZero() && now.Before(record.NotBefore) {
		return ctx, ErrInvalidOAuth2Token
	}
	if !record.ExpiresAt.IsZero() && !now.Before(record.ExpiresAt) {
		return ctx, ErrInvalidOAuth2Token
	}
	for _, scope := range requiredScopes {
		if !slices.Contains(record.Scopes, scope) {
			return ctx, ErrOAuth2Forbidden
		}
	}
	identity := OAuth2Identity{Subject: record.Subject, ClientID: record.ClientID, Scopes: slices.Clone(record.Scopes)}
	return context.WithValue(ctx, oauth2ContextKey{scheme: scheme}, identity), nil
}

// handler implements api.SecurityHandler. Unsupported schemes remain stubs.
type handler struct {
	apiKeys      APIKeyStore
	basicAuth    BasicAuthStore
	passwords    PasswordVerifier
	bearerTokens BearerTokenVerifier
	oauth2Tokens OAuth2TokenVerifier
}

// NewHandler creates a security handler. Nil dependencies reject requests for their schemes.
func NewHandler(apiKeys APIKeyStore, basicAuth BasicAuthStore, passwords PasswordVerifier, bearerTokens BearerTokenVerifier, oauth2Tokens OAuth2TokenVerifier) *handler {
	return &handler{apiKeys: apiKeys, basicAuth: basicAuth, passwords: passwords, bearerTokens: bearerTokens, oauth2Tokens: oauth2Tokens}
}

var _ api.SecurityHandler = (*handler)(nil)

// HandleApiKeyCookieM2xJf implements api.SecurityHandler.
func (s *handler) HandleApiKeyCookieM2xJf(ctx context.Context, _ api.OperationName, credentials api.ApiKeyCookieM2xJf) (context.Context, error) {
	return s.authorizeAPIKey(ctx, "ApiKeyCookieM2xJf", credentials.APIKey, credentials.Roles)
}

// HandleApiKeyHeaderA3nKs implements api.SecurityHandler.
func (s *handler) HandleApiKeyHeaderA3nKs(ctx context.Context, _ api.OperationName, credentials api.ApiKeyHeaderA3nKs) (context.Context, error) {
	return s.authorizeAPIKey(ctx, "ApiKeyHeaderA3nKs", credentials.APIKey, credentials.Roles)
}

// HandleApiKeyQueryC8rVw implements api.SecurityHandler.
func (s *handler) HandleApiKeyQueryC8rVw(ctx context.Context, _ api.OperationName, credentials api.ApiKeyQueryC8rVw) (context.Context, error) {
	return s.authorizeAPIKey(ctx, "ApiKeyQueryC8rVw", credentials.APIKey, credentials.Roles)
}

// HandleBasicAuthF5wJz implements api.SecurityHandler.
func (s *handler) HandleBasicAuthF5wJz(ctx context.Context, _ api.OperationName, credentials api.BasicAuthF5wJz) (context.Context, error) {
	return s.authorizeBasicAuth(ctx, "BasicAuthF5wJz", credentials.Username, credentials.Password, credentials.Roles)
}

// HandleBearerAuthV6qPt implements api.SecurityHandler.
func (s *handler) HandleBearerAuthV6qPt(ctx context.Context, _ api.OperationName, credentials api.BearerAuthV6qPt) (context.Context, error) {
	return s.authorizeBearerAuth(ctx, "BearerAuthV6qPt", credentials.Token, credentials.Roles)
}

// HandleOAuth2N4kXb implements api.SecurityHandler.
func (s *handler) HandleOAuth2N4kXb(ctx context.Context, _ api.OperationName, credentials api.OAuth2N4kXb) (context.Context, error) {
	return s.authorizeOAuth2(ctx, "OAuth2N4kXb", credentials.Token, credentials.Scopes)
}

// HandleReferencedBearerAuthZ8yHd implements api.SecurityHandler.
func (s *handler) HandleReferencedBearerAuthZ8yHd(ctx context.Context, _ api.OperationName, credentials api.ReferencedBearerAuthZ8yHd) (context.Context, error) {
	return s.authorizeBearerAuth(ctx, "ReferencedBearerAuthZ8yHd", credentials.Token, credentials.Roles)
}
