// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AlternativeAuthenticationV8xNpOperation OperationName = "AlternativeAuthenticationV8xNp"
	ApiKeyCookieD4tZuOperation              OperationName = "ApiKeyCookieD4tZu"
	ApiKeyHeaderL5mQaOperation              OperationName = "ApiKeyHeaderL5mQa"
	ApiKeyQueryW7pErOperation               OperationName = "ApiKeyQueryW7pEr"
	ApiKeyWithRoleP9bLcOperation            OperationName = "ApiKeyWithRoleP9bLc"
	BasicAuthenticationE6qRtOperation       OperationName = "BasicAuthenticationE6qRt"
	BearerAuthenticationT3nVkOperation      OperationName = "BearerAuthenticationT3nVk"
	ComplexAuthenticationG9wTcOperation     OperationName = "ComplexAuthenticationG9wTc"
	InheritedSecurityF3vNxOperation         OperationName = "InheritedSecurityF3vNx"
	Oauth2AuthenticationM2cFwOperation      OperationName = "Oauth2AuthenticationM2cFw"
	Oauth2WithoutScopesB7vQeOperation       OperationName = "Oauth2WithoutScopesB7vQe"
	OptionalAuthenticationC2yHsOperation    OperationName = "OptionalAuthenticationC2yHs"
	PublicEndpointR8kWdOperation            OperationName = "PublicEndpointR8kWd"
	ReferencedSecuritySchemeU2kMfOperation  OperationName = "ReferencedSecuritySchemeU2kMf"
)
