// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/validate"
)

func decodeAlternativeAuthenticationV8xNpResponse(resp *http.Response) (res *AlternativeAuthenticationV8xNpOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &AlternativeAuthenticationV8xNpOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeApiKeyCookieD4tZuResponse(resp *http.Response) (res *ApiKeyCookieD4tZuOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ApiKeyCookieD4tZuOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeApiKeyHeaderL5mQaResponse(resp *http.Response) (res *ApiKeyHeaderL5mQaOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ApiKeyHeaderL5mQaOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeApiKeyQueryW7pErResponse(resp *http.Response) (res *ApiKeyQueryW7pErOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ApiKeyQueryW7pErOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeApiKeyWithRoleP9bLcResponse(resp *http.Response) (res *ApiKeyWithRoleP9bLcOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ApiKeyWithRoleP9bLcOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeBasicAuthenticationE6qRtResponse(resp *http.Response) (res *BasicAuthenticationE6qRtOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &BasicAuthenticationE6qRtOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeBearerAuthenticationT3nVkResponse(resp *http.Response) (res *BearerAuthenticationT3nVkOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &BearerAuthenticationT3nVkOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeComplexAuthenticationG9wTcResponse(resp *http.Response) (res *ComplexAuthenticationG9wTcOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ComplexAuthenticationG9wTcOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeInheritedSecurityF3vNxResponse(resp *http.Response) (res *InheritedSecurityF3vNxOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &InheritedSecurityF3vNxOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeOauth2AuthenticationM2cFwResponse(resp *http.Response) (res *Oauth2AuthenticationM2cFwOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &Oauth2AuthenticationM2cFwOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeOauth2WithoutScopesB7vQeResponse(resp *http.Response) (res *Oauth2WithoutScopesB7vQeOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &Oauth2WithoutScopesB7vQeOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeOptionalAuthenticationC2yHsResponse(resp *http.Response) (res *OptionalAuthenticationC2yHsOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &OptionalAuthenticationC2yHsOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodePublicEndpointR8kWdResponse(resp *http.Response) (res *PublicEndpointR8kWdOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &PublicEndpointR8kWdOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}

func decodeReferencedSecuritySchemeU2kMfResponse(resp *http.Response) (res *ReferencedSecuritySchemeU2kMfOK, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &ReferencedSecuritySchemeU2kMfOK{}, nil
	}
	return res, validate.UnexpectedStatusCodeWithResponse(resp)
}
