// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AlternativeAuthenticationV8xNp implements alternativeAuthenticationV8xNp operation.
//
// Accepts any of the listed alternative authentication mechanisms.
//
// GET /orq5lzc
func (UnimplementedHandler) AlternativeAuthenticationV8xNp(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ApiKeyCookieD4tZu implements apiKeyCookieD4tZu operation.
//
// Requires an API key passed through a cookie.
//
// GET /api-key-cookieh8ryu
func (UnimplementedHandler) ApiKeyCookieD4tZu(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ApiKeyHeaderL5mQa implements apiKeyHeaderL5mQa operation.
//
// Requires an API key passed through the request header.
//
// GET /api-key-headerx3nws
func (UnimplementedHandler) ApiKeyHeaderL5mQa(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ApiKeyQueryW7pEr implements apiKeyQueryW7pEr operation.
//
// Requires an API key passed through a query parameter.
//
// GET /api-key-queryc6jfa
func (UnimplementedHandler) ApiKeyQueryW7pEr(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ApiKeyWithRoleP9bLc implements apiKeyWithRoleP9bLc operation.
//
// Requires an API key accompanied by the admin role requirement.
//
// GET /api-key-with-rolek2vdp
func (UnimplementedHandler) ApiKeyWithRoleP9bLc(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// BasicAuthenticationE6qRt implements basicAuthenticationE6qRt operation.
//
// Requires HTTP Basic authentication.
//
// GET /basicn5sge
func (UnimplementedHandler) BasicAuthenticationE6qRt(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// BearerAuthenticationT3nVk implements bearerAuthenticationT3nVk operation.
//
// Requires HTTP Bearer authentication.
//
// GET /bearerw7cqm
func (UnimplementedHandler) BearerAuthenticationT3nVk(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ComplexAuthenticationG9wTc implements complexAuthenticationG9wTc operation.
//
// Accepts one of the documented combined authentication alternatives.
//
// GET /and-orf7kpd
func (UnimplementedHandler) ComplexAuthenticationG9wTc(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// InheritedSecurityF3vNx implements inheritedSecurityF3vNx operation.
//
// Inherits the global BearerAuth requirement.
//
// GET /inherited-securitya8k2z
func (UnimplementedHandler) InheritedSecurityF3vNx(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// Oauth2AuthenticationM2cFw implements oauth2AuthenticationM2cFw operation.
//
// Requires OAuth 2.0 authentication with read and write scopes.
//
// GET /oauth2z6pua
func (UnimplementedHandler) Oauth2AuthenticationM2cFw(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// Oauth2WithoutScopesB7vQe implements oauth2WithoutScopesB7vQe operation.
//
// Requires OAuth 2.0 authentication without specific scopes.
//
// GET /oauth2-without-scopesd3wnf
func (UnimplementedHandler) Oauth2WithoutScopesB7vQe(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// OptionalAuthenticationC2yHs implements optionalAuthenticationC2yHs operation.
//
// Allows either anonymous access or BearerAuth authentication.
//
// GET /optional-authenticationp9tql
func (UnimplementedHandler) OptionalAuthenticationC2yHs(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// PublicEndpointR8kWd implements publicEndpointR8kWd operation.
//
// Public endpoint that overrides the global security requirement.
//
// GET /publicm4vrb
func (UnimplementedHandler) PublicEndpointR8kWd(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// ReferencedSecuritySchemeU2kMf implements referencedSecuritySchemeU2kMf operation.
//
// Requires a referenced bearer authentication security scheme.
//
// GET /referenced-security-schemer4cnj
func (UnimplementedHandler) ReferencedSecuritySchemeU2kMf(ctx context.Context) error {
	return ht.ErrNotImplemented
}
