// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AlternativeAuthenticationV8xNp implements alternativeAuthenticationV8xNp operation.
	//
	// Accepts any of the listed alternative authentication mechanisms.
	//
	// GET /orq5lzc
	AlternativeAuthenticationV8xNp(ctx context.Context) error
	// ApiKeyCookieD4tZu implements apiKeyCookieD4tZu operation.
	//
	// Requires an API key passed through a cookie.
	//
	// GET /api-key-cookieh8ryu
	ApiKeyCookieD4tZu(ctx context.Context) error
	// ApiKeyHeaderL5mQa implements apiKeyHeaderL5mQa operation.
	//
	// Requires an API key passed through the request header.
	//
	// GET /api-key-headerx3nws
	ApiKeyHeaderL5mQa(ctx context.Context) error
	// ApiKeyQueryW7pEr implements apiKeyQueryW7pEr operation.
	//
	// Requires an API key passed through a query parameter.
	//
	// GET /api-key-queryc6jfa
	ApiKeyQueryW7pEr(ctx context.Context) error
	// ApiKeyWithRoleP9bLc implements apiKeyWithRoleP9bLc operation.
	//
	// Requires an API key accompanied by the admin role requirement.
	//
	// GET /api-key-with-rolek2vdp
	ApiKeyWithRoleP9bLc(ctx context.Context) error
	// BasicAuthenticationE6qRt implements basicAuthenticationE6qRt operation.
	//
	// Requires HTTP Basic authentication.
	//
	// GET /basicn5sge
	BasicAuthenticationE6qRt(ctx context.Context) error
	// BearerAuthenticationT3nVk implements bearerAuthenticationT3nVk operation.
	//
	// Requires HTTP Bearer authentication.
	//
	// GET /bearerw7cqm
	BearerAuthenticationT3nVk(ctx context.Context) error
	// ComplexAuthenticationG9wTc implements complexAuthenticationG9wTc operation.
	//
	// Accepts one of the documented combined authentication alternatives.
	//
	// GET /and-orf7kpd
	ComplexAuthenticationG9wTc(ctx context.Context) error
	// InheritedSecurityF3vNx implements inheritedSecurityF3vNx operation.
	//
	// Inherits the global BearerAuth requirement.
	//
	// GET /inherited-securitya8k2z
	InheritedSecurityF3vNx(ctx context.Context) error
	// Oauth2AuthenticationM2cFw implements oauth2AuthenticationM2cFw operation.
	//
	// Requires OAuth 2.0 authentication with read and write scopes.
	//
	// GET /oauth2z6pua
	Oauth2AuthenticationM2cFw(ctx context.Context) error
	// Oauth2WithoutScopesB7vQe implements oauth2WithoutScopesB7vQe operation.
	//
	// Requires OAuth 2.0 authentication without specific scopes.
	//
	// GET /oauth2-without-scopesd3wnf
	Oauth2WithoutScopesB7vQe(ctx context.Context) error
	// OptionalAuthenticationC2yHs implements optionalAuthenticationC2yHs operation.
	//
	// Allows either anonymous access or BearerAuth authentication.
	//
	// GET /optional-authenticationp9tql
	OptionalAuthenticationC2yHs(ctx context.Context) error
	// PublicEndpointR8kWd implements publicEndpointR8kWd operation.
	//
	// Public endpoint that overrides the global security requirement.
	//
	// GET /publicm4vrb
	PublicEndpointR8kWd(ctx context.Context) error
	// ReferencedSecuritySchemeU2kMf implements referencedSecuritySchemeU2kMf operation.
	//
	// Requires a referenced bearer authentication security scheme.
	//
	// GET /referenced-security-schemer4cnj
	ReferencedSecuritySchemeU2kMf(ctx context.Context) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
