// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleApiKeyCookieM2xJf handles ApiKeyCookieM2xJf security.
	// API key passed through a cookie.
	HandleApiKeyCookieM2xJf(ctx context.Context, operationName OperationName, t ApiKeyCookieM2xJf) (context.Context, error)
	// HandleApiKeyHeaderA3nKs handles ApiKeyHeaderA3nKs security.
	// API key passed through an HTTP header.
	HandleApiKeyHeaderA3nKs(ctx context.Context, operationName OperationName, t ApiKeyHeaderA3nKs) (context.Context, error)
	// HandleApiKeyQueryC8rVw handles ApiKeyQueryC8rVw security.
	// API key passed through a query parameter.
	HandleApiKeyQueryC8rVw(ctx context.Context, operationName OperationName, t ApiKeyQueryC8rVw) (context.Context, error)
	// HandleBasicAuthF5wJz handles BasicAuthF5wJz security.
	// HTTP Basic authentication.
	HandleBasicAuthF5wJz(ctx context.Context, operationName OperationName, t BasicAuthF5wJz) (context.Context, error)
	// HandleBearerAuthV6qPt handles BearerAuthV6qPt security.
	// HTTP Bearer authentication using JWT.
	HandleBearerAuthV6qPt(ctx context.Context, operationName OperationName, t BearerAuthV6qPt) (context.Context, error)
	// HandleOAuth2N4kXb handles OAuth2N4kXb security.
	// OAuth 2.0 supporting all flows defined by OpenAPI.
	HandleOAuth2N4kXb(ctx context.Context, operationName OperationName, t OAuth2N4kXb) (context.Context, error)
	// HandleReferencedBearerAuthZ8yHd handles ReferencedBearerAuthZ8yHd security.
	// HTTP Bearer authentication using JWT.
	HandleReferencedBearerAuthZ8yHd(ctx context.Context, operationName OperationName, t ReferencedBearerAuthZ8yHd) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesApiKeyCookieM2xJf is a private map storing roles per operation.
var operationRolesApiKeyCookieM2xJf = map[string][]string{
	ApiKeyCookieD4tZuOperation: []string{},
}

// GetRolesForApiKeyCookieM2xJf returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyCookieM2xJf(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyCookieM2xJf(operation string) []string {
	roles, ok := operationRolesApiKeyCookieM2xJf[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesApiKeyHeaderA3nKs is a private map storing roles per operation.
var operationRolesApiKeyHeaderA3nKs = map[string][]string{
	AlternativeAuthenticationV8xNpOperation: []string{},
	ApiKeyHeaderL5mQaOperation:              []string{},
	ApiKeyWithRoleP9bLcOperation: []string{
		"adminB2vXc",
	},
	ComplexAuthenticationG9wTcOperation: []string{},
}

// GetRolesForApiKeyHeaderA3nKs returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyHeaderA3nKs(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyHeaderA3nKs(operation string) []string {
	roles, ok := operationRolesApiKeyHeaderA3nKs[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesApiKeyQueryC8rVw is a private map storing roles per operation.
var operationRolesApiKeyQueryC8rVw = map[string][]string{
	ApiKeyQueryW7pErOperation: []string{},
}

// GetRolesForApiKeyQueryC8rVw returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyQueryC8rVw(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyQueryC8rVw(operation string) []string {
	roles, ok := operationRolesApiKeyQueryC8rVw[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesBasicAuthF5wJz is a private map storing roles per operation.
var operationRolesBasicAuthF5wJz = map[string][]string{
	BasicAuthenticationE6qRtOperation: []string{},
}

// GetRolesForBasicAuthF5wJz returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBasicAuthF5wJz(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBasicAuthF5wJz(operation string) []string {
	roles, ok := operationRolesBasicAuthF5wJz[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesBearerAuthV6qPt is a private map storing roles per operation.
var operationRolesBearerAuthV6qPt = map[string][]string{
	AlternativeAuthenticationV8xNpOperation: []string{},
	BearerAuthenticationT3nVkOperation:      []string{},
	InheritedSecurityF3vNxOperation:         []string{},
	OptionalAuthenticationC2yHsOperation:    []string{},
}

// GetRolesForBearerAuthV6qPt returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuthV6qPt(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuthV6qPt(operation string) []string {
	roles, ok := operationRolesBearerAuthV6qPt[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// oauth2ScopesOAuth2N4kXb is a private map storing OAuth2 scopes per operation.
var oauth2ScopesOAuth2N4kXb = map[string][]string{
	ComplexAuthenticationG9wTcOperation: []string{
		"readK4mZq",
	},
	Oauth2AuthenticationM2cFwOperation: []string{
		"readK4mZq",
		"writeH7pLs",
	},
	Oauth2WithoutScopesB7vQeOperation: []string{},
}

// GetOAuth2ScopesForOAuth2N4kXb returns the required OAuth2 scopes for the given operation.
//
// This is useful for token exchange scenarios where you need to know which scopes
// to request when obtaining a token for a downstream API call.
//
// Example:
//
//	requiredScopes := GetOAuth2ScopesForOAuth2N4kXb(AddPetOperation)
//	token := exchangeTokenWithScopes(requiredScopes, "https://api.example.com")
//
// Returns nil if the operation has no scope requirements or if the operation is unknown.
func GetOAuth2ScopesForOAuth2N4kXb(operation string) []string {
	scopes, ok := oauth2ScopesOAuth2N4kXb[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(scopes))
	copy(result, scopes)
	return result
}

// operationRolesReferencedBearerAuthZ8yHd is a private map storing roles per operation.
var operationRolesReferencedBearerAuthZ8yHd = map[string][]string{
	ReferencedSecuritySchemeU2kMfOperation: []string{},
}

// GetRolesForReferencedBearerAuthZ8yHd returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForReferencedBearerAuthZ8yHd(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForReferencedBearerAuthZ8yHd(operation string) []string {
	roles, ok := operationRolesReferencedBearerAuthZ8yHd[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityApiKeyCookieM2xJf(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiKeyCookieM2xJf
	const parameterName = "api_key_t9pds"
	var value string
	switch cookie, err := req.Cookie(parameterName); {
	case err == nil: // if NO error
		value = cookie.Value
	case errors.Is(err, http.ErrNoCookie):
		return ctx, false, nil
	default:
		return nil, false, errors.Wrap(err, "get cookie value")
	}
	t.APIKey = value
	t.Roles = operationRolesApiKeyCookieM2xJf[operationName]
	rctx, err := s.sec.HandleApiKeyCookieM2xJf(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityApiKeyHeaderA3nKs(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiKeyHeaderA3nKs
	const parameterName = "X-Api-Key-L7nqe"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesApiKeyHeaderA3nKs[operationName]
	rctx, err := s.sec.HandleApiKeyHeaderA3nKs(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityApiKeyQueryC8rVw(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiKeyQueryC8rVw
	const parameterName = "api_key_r4xmv"
	q := req.URL.Query()
	if !q.Has(parameterName) {
		return ctx, false, nil
	}
	value := q.Get(parameterName)
	t.APIKey = value
	t.Roles = operationRolesApiKeyQueryC8rVw[operationName]
	rctx, err := s.sec.HandleApiKeyQueryC8rVw(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityBasicAuthF5wJz(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BasicAuthF5wJz
	if _, ok := findAuthorization(req.Header, "Basic"); !ok {
		return ctx, false, nil
	}
	username, password, ok := req.BasicAuth()
	if !ok {
		return nil, false, errors.New("invalid basic auth")
	}
	t.Username = username
	t.Password = password
	t.Roles = operationRolesBasicAuthF5wJz[operationName]
	rctx, err := s.sec.HandleBasicAuthF5wJz(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityBearerAuthV6qPt(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuthV6qPt
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuthV6qPt[operationName]
	rctx, err := s.sec.HandleBearerAuthV6qPt(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityOAuth2N4kXb(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t OAuth2N4kXb
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Scopes = oauth2ScopesOAuth2N4kXb[operationName]
	rctx, err := s.sec.HandleOAuth2N4kXb(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityReferencedBearerAuthZ8yHd(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ReferencedBearerAuthZ8yHd
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesReferencedBearerAuthZ8yHd[operationName]
	rctx, err := s.sec.HandleReferencedBearerAuthZ8yHd(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKeyCookieM2xJf provides ApiKeyCookieM2xJf security value.
	// API key passed through a cookie.
	ApiKeyCookieM2xJf(ctx context.Context, operationName OperationName) (ApiKeyCookieM2xJf, error)
	// ApiKeyHeaderA3nKs provides ApiKeyHeaderA3nKs security value.
	// API key passed through an HTTP header.
	ApiKeyHeaderA3nKs(ctx context.Context, operationName OperationName) (ApiKeyHeaderA3nKs, error)
	// ApiKeyQueryC8rVw provides ApiKeyQueryC8rVw security value.
	// API key passed through a query parameter.
	ApiKeyQueryC8rVw(ctx context.Context, operationName OperationName) (ApiKeyQueryC8rVw, error)
	// BasicAuthF5wJz provides BasicAuthF5wJz security value.
	// HTTP Basic authentication.
	BasicAuthF5wJz(ctx context.Context, operationName OperationName) (BasicAuthF5wJz, error)
	// BearerAuthV6qPt provides BearerAuthV6qPt security value.
	// HTTP Bearer authentication using JWT.
	BearerAuthV6qPt(ctx context.Context, operationName OperationName) (BearerAuthV6qPt, error)
	// OAuth2N4kXb provides OAuth2N4kXb security value.
	// OAuth 2.0 supporting all flows defined by OpenAPI.
	OAuth2N4kXb(ctx context.Context, operationName OperationName) (OAuth2N4kXb, error)
	// ReferencedBearerAuthZ8yHd provides ReferencedBearerAuthZ8yHd security value.
	// HTTP Bearer authentication using JWT.
	ReferencedBearerAuthZ8yHd(ctx context.Context, operationName OperationName) (ReferencedBearerAuthZ8yHd, error)
}

func (s *Client) securityApiKeyCookieM2xJf(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyCookieM2xJf(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyCookieM2xJf\"")
	}
	req.AddCookie(&http.Cookie{
		Name:  "api_key_t9pds",
		Value: t.APIKey,
	})
	return nil
}
func (s *Client) securityApiKeyHeaderA3nKs(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyHeaderA3nKs(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyHeaderA3nKs\"")
	}
	req.Header.Set("X-Api-Key-L7nqe", t.APIKey)
	return nil
}
func (s *Client) securityApiKeyQueryC8rVw(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyQueryC8rVw(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyQueryC8rVw\"")
	}
	q := req.URL.Query()
	q.Set("api_key_r4xmv", t.APIKey)
	req.URL.RawQuery = q.Encode()
	return nil
}
func (s *Client) securityBasicAuthF5wJz(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BasicAuthF5wJz(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BasicAuthF5wJz\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
func (s *Client) securityBearerAuthV6qPt(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuthV6qPt(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuthV6qPt\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityOAuth2N4kXb(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.OAuth2N4kXb(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"OAuth2N4kXb\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityReferencedBearerAuthZ8yHd(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ReferencedBearerAuthZ8yHd(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ReferencedBearerAuthZ8yHd\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
