// Code generated by ogen, DO NOT EDIT.

package api

// AlternativeAuthenticationV8xNpOK is response for AlternativeAuthenticationV8xNp operation.
type AlternativeAuthenticationV8xNpOK struct{}

// ApiKeyCookieD4tZuOK is response for ApiKeyCookieD4tZu operation.
type ApiKeyCookieD4tZuOK struct{}

type ApiKeyCookieM2xJf struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyCookieM2xJf) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ApiKeyCookieM2xJf) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyCookieM2xJf) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ApiKeyCookieM2xJf) SetRoles(val []string) {
	s.Roles = val
}

type ApiKeyHeaderA3nKs struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyHeaderA3nKs) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ApiKeyHeaderA3nKs) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyHeaderA3nKs) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ApiKeyHeaderA3nKs) SetRoles(val []string) {
	s.Roles = val
}

// ApiKeyHeaderL5mQaOK is response for ApiKeyHeaderL5mQa operation.
type ApiKeyHeaderL5mQaOK struct{}

type ApiKeyQueryC8rVw struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *ApiKeyQueryC8rVw) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *ApiKeyQueryC8rVw) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *ApiKeyQueryC8rVw) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *ApiKeyQueryC8rVw) SetRoles(val []string) {
	s.Roles = val
}

// ApiKeyQueryW7pErOK is response for ApiKeyQueryW7pEr operation.
type ApiKeyQueryW7pErOK struct{}

// ApiKeyWithRoleP9bLcOK is response for ApiKeyWithRoleP9bLc operation.
type ApiKeyWithRoleP9bLcOK struct{}

type BasicAuthF5wJz struct {
	Username string
	Password string
	Roles    []string
}

// GetUsername returns the value of Username.
func (s *BasicAuthF5wJz) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *BasicAuthF5wJz) GetPassword() string {
	return s.Password
}

// GetRoles returns the value of Roles.
func (s *BasicAuthF5wJz) GetRoles() []string {
	return s.Roles
}

// SetUsername sets the value of Username.
func (s *BasicAuthF5wJz) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *BasicAuthF5wJz) SetPassword(val string) {
	s.Password = val
}

// SetRoles sets the value of Roles.
func (s *BasicAuthF5wJz) SetRoles(val []string) {
	s.Roles = val
}

// BasicAuthenticationE6qRtOK is response for BasicAuthenticationE6qRt operation.
type BasicAuthenticationE6qRtOK struct{}

type BearerAuthV6qPt struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuthV6qPt) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuthV6qPt) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuthV6qPt) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuthV6qPt) SetRoles(val []string) {
	s.Roles = val
}

// BearerAuthenticationT3nVkOK is response for BearerAuthenticationT3nVk operation.
type BearerAuthenticationT3nVkOK struct{}

// ComplexAuthenticationG9wTcOK is response for ComplexAuthenticationG9wTc operation.
type ComplexAuthenticationG9wTcOK struct{}

// InheritedSecurityF3vNxOK is response for InheritedSecurityF3vNx operation.
type InheritedSecurityF3vNxOK struct{}

type OAuth2N4kXb struct {
	Token  string
	Scopes []string
}

// GetToken returns the value of Token.
func (s *OAuth2N4kXb) GetToken() string {
	return s.Token
}

// GetScopes returns the value of Scopes.
func (s *OAuth2N4kXb) GetScopes() []string {
	return s.Scopes
}

// SetToken sets the value of Token.
func (s *OAuth2N4kXb) SetToken(val string) {
	s.Token = val
}

// SetScopes sets the value of Scopes.
func (s *OAuth2N4kXb) SetScopes(val []string) {
	s.Scopes = val
}

// Oauth2AuthenticationM2cFwOK is response for Oauth2AuthenticationM2cFw operation.
type Oauth2AuthenticationM2cFwOK struct{}

// Oauth2WithoutScopesB7vQeOK is response for Oauth2WithoutScopesB7vQe operation.
type Oauth2WithoutScopesB7vQeOK struct{}

// OptionalAuthenticationC2yHsOK is response for OptionalAuthenticationC2yHs operation.
type OptionalAuthenticationC2yHsOK struct{}

// PublicEndpointR8kWdOK is response for PublicEndpointR8kWd operation.
type PublicEndpointR8kWdOK struct{}

type ReferencedBearerAuthZ8yHd struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *ReferencedBearerAuthZ8yHd) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *ReferencedBearerAuthZ8yHd) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *ReferencedBearerAuthZ8yHd) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *ReferencedBearerAuthZ8yHd) SetRoles(val []string) {
	s.Roles = val
}

// ReferencedSecuritySchemeU2kMfOK is response for ReferencedSecuritySchemeU2kMf operation.
type ReferencedSecuritySchemeU2kMfOK struct{}
