// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"go.opentelemetry.io/otel/trace"
)

func encodeAlternativeAuthenticationV8xNpResponse(response *AlternativeAuthenticationV8xNpOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeApiKeyCookieD4tZuResponse(response *ApiKeyCookieD4tZuOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeApiKeyHeaderL5mQaResponse(response *ApiKeyHeaderL5mQaOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeApiKeyQueryW7pErResponse(response *ApiKeyQueryW7pErOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeApiKeyWithRoleP9bLcResponse(response *ApiKeyWithRoleP9bLcOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeBasicAuthenticationE6qRtResponse(response *BasicAuthenticationE6qRtOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeBearerAuthenticationT3nVkResponse(response *BearerAuthenticationT3nVkOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeComplexAuthenticationG9wTcResponse(response *ComplexAuthenticationG9wTcOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeInheritedSecurityF3vNxResponse(response *InheritedSecurityF3vNxOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeOauth2AuthenticationM2cFwResponse(response *Oauth2AuthenticationM2cFwOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeOauth2WithoutScopesB7vQeResponse(response *Oauth2WithoutScopesB7vQeOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeOptionalAuthenticationC2yHsResponse(response *OptionalAuthenticationC2yHsOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodePublicEndpointR8kWdResponse(response *PublicEndpointR8kWdOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}

func encodeReferencedSecuritySchemeU2kMfResponse(response *ReferencedSecuritySchemeU2kMfOK, w http.ResponseWriter, span trace.Span) error {
	w.WriteHeader(200)

	return nil
}
